# use Powershell instead of sh:
set shell := ["powershell.exe", "-c"]

build:
    # the first run of pdflatex is only needed to generate the .aux file for bibtex, don't run it if the file already exists
    (Test-Path -Path ../bin/thesis.aux) -or (pdflatex --interaction=batchmode --output-directory=..\bin -shell-escape .\thesis.tex) | out-null
    bibtex ..\bin\thesis.aux
    pdflatex --interaction=batchmode --output-directory=..\bin -shell-escape .\thesis.tex
    pdflatex --interaction=batchmode --output-directory=..\bin -shell-escape .\thesis.tex
    cp ..\bin\thesis.pdf ..

clean:
    rm -r ..\bin
    rm ..\thesis.pdf
